version: '3.8'

services:
  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: ./quic_shell_server
