# Use an official Go runtime as a parent image
FROM golang:1.21-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Download dependencies
RUN go mod download

# Build your application
RUN go build -o quic_shell_server .

# Run the application when the container starts
CMD ["./quic_shell_server"]
