version: '3.8'

services:
  websocket-server:
    container_name: wt-server
    build:
      #context: /Users/won/lab/buildtools/helpers/golang/commons/app/remote_shell/quic_shell/server
      context: ..
      dockerfile: .devops/dockerfile
    ports:
      - "80:4242"
    environment:
      AWS_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: ""
      AWS_ACCESS_KEY_ID: ""
      DEFAULT_DOCKER_IMAGE: dawnbreather/amazonlinux2:systemd-tntk-latest
      DEFAULT_DOCKER_CONTAINER_SHELL: /bin/bash
    volumes:
      #- .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: /app/quic_shell_server
