# Use an official Go runtime as a parent image
FROM golang:1.21-alpine as build

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Download dependencies
RUN go mod download

# Build your application
RUN go build -o /app/quic_shell_server main/main.go

FROM debian:latest as app

COPY --from=build /app/quic_shell_server /app/quic_shell_server

# Run the application when the container starts
CMD ["/app/quic_shell_server"]
