version: '3.8'

services:
  websocket-server:
    container_name: wt-server
    build:
      #context: /Users/won/lab/buildtools/helpers/golang/commons/app/remote_shell/quic_shell/server
      context: ..
      dockerfile: .devops/dockerfile
    ports:
      - "4242:4242"
    volumes:
      #- .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: /app/quic_shell_server
